# Generated by Django 6.0.5 on 2026-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('establishment_type', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('CAFETERIA', 'Cafetería'), ('BAR', 'Bar'), ('OTRO', 'Otro')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
