# Generated by Django 6.0.5 on 2026-06-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('CAFETERIA', 'Cafetería'), ('BAR', 'Bar'), ('HUECA', 'Hueca Tradicional'), ('OTRO', 'Otro')], default='RESTAURANTE', max_length=20),
        ),
    ]
