# Generated by Django 6.0.5 on 2026-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0003_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
